# Generated by Django 3.0.4 on 2020-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatper_number', models.IntegerField(unique=True, verbose_name="Chapter's Number")),
                ('chapter_name', models.CharField(max_length=100, verbose_name="Chapter's Name")),
                ('chapter_summary', models.TextField(max_length=10000, verbose_name="Chapter's Summary")),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(unique=True, verbose_name="Question's Number")),
                ('question_description', models.SlugField(max_length=10000, verbose_name="Question's Description")),
                ('question_answer', models.CharField(max_length=10000, verbose_name="Question's answer")),
                ('question_howtodo', models.CharField(max_length=10000, verbose_name="Question's how to do")),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_number', models.IntegerField(unique=True, verbose_name="Subject's Number")),
                ('subject_name', models.CharField(max_length=100, verbose_name="Subject's Name")),
                ('subject_chapters', models.ManyToManyField(to='questionbank.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_questions',
            field=models.ManyToManyField(to='questionbank.Question'),
        ),
    ]
