# Generated by Django 3.0.4 on 2020-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_auto_20200331_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.TextField(max_length=10000, verbose_name="Question's answer"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_howtodo',
            field=models.TextField(max_length=10000, verbose_name="Question's how to do"),
        ),
    ]
