# Generated by Django 3.0.4 on 2020-03-31 10:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_auto_20200331_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_summary',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name="Chapter's Summary"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name="Question's answer"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name="Question's Description"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_howtodo',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name="Question's how to do"),
        ),
    ]
