# Generated by Django 3.0.4 on 2020-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0004_auto_20200331_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_howtodo',
        ),
        migrations.AddField(
            model_name='question',
            name='question_attr',
            field=models.CharField(choices=[('E', 'EASY'), ('M', 'MEDIUM'), ('H', 'HARD')], default='E', max_length=2, verbose_name='Toughness'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_summary',
            field=models.TextField(max_length=10000, verbose_name="Chapter's Summary"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.TextField(max_length=10000, verbose_name="Question's answer"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_description',
            field=models.TextField(max_length=10000, verbose_name="Question's Description"),
        ),
    ]
