# Generated by Django 3.0.4 on 2020-04-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0005_auto_20200403_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_attr',
            field=models.CharField(choices=[('btn-success', 'EASY'), ('btn-warning', 'MEDIUM'), ('btn-danger', 'HARD')], default='btn-success', max_length=12, verbose_name='Toughness'),
        ),
    ]
